// export const isLoading = state => state.isLoading
// export const isRunNative = state => state.isRunNative
// export const params = state => state.params
// export const paramsStack = state => state.paramsStack
// export const backParams = state => state.backParams
// export const backPopPageNumbs = state => state.backPopPageNumbs
// export const backState = state => state.backState
// export const appTitle = state => state.appTitle
// export const appTitleBarVisible = state => state.appTitleBarVisible
// export const appTitleBarBackBtnVisible = state => state.appTitleBarBackBtnVisible
// export const isLogined = state => state.isLogined
// export const deviceInfos = state => state.deviceInfos
// export const sessionTimeoutDialogState = state => state.sessionTimeoutDialogState
